### ISSUE TITLE
live-installer: crash when the Expert mode button pressed if /target mount is empty

### ISSUE THREAD

**Issue by morton-f** [linuxmint/lmde6-beta#10]
Failing to mount anything to `/target` as required in the expert mode is causing the immidiate crush after clicking the _expert mode_ button. Installer just disappears without a trace. When /target was correctly mounted to /dev/mapper device I managed to install LMDE6 successfully.

**Comment by clefebvre** [comment]
Fixed in live-installer 2023.09.15.
