### ISSUE TITLE
packages: zstd is missing

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/lmde6-beta#11]
I installed in Virtual box.
Update detected a later kernel, but during the install it gave a warning:-

W: No zstd in /usr/bin:/sbin:/bin, using gzip

It still works, but apparently zstd is missing?
```
$ zstd --help
Command 'zstd' not found, but can be installed with:
sudo apt install zstd
```

**Comment by Xdavius** [comment]
Up. Missing zstd. This must be corrected. Thank you

**Comment by clefebvre** [comment]
Added for upcoming ISOs.
