### ISSUE TITLE
cinnamon: window list applet is right-justified

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/lmde6-beta#12]
Running in Virtualbox:-

The Window List is right-justified on the panel.
Obviously this could be a "feature" - but I'd consider the LMDE5 version (left-justified) to be preferable.

![Screenshot from 2023-09-14 12-44-29](https://github.com/linuxmint/lmde6-beta/assets/52585119/97a12a18-b262-4957-afc8-e423c5b14395)

**Comment by clefebvre** [comment]
Right-click the panel and enable panel-edit-mode. I'd like to make sure you placed this applet in the left zone.

**Comment by Jeremy7701** [comment]
Unfortunately, the window list is in the right zone:-
![Screenshot from 2023-09-15 11-11-42](https://github.com/linuxmint/lmde6-beta/assets/52585119/4fc17961-38d3-431f-8f8f-c6e687207dda)

**Comment by clefebvre** [comment]
OK that's why it goes on the right. The right zone is right-aligned, the left zone is left-aligned and the center zone is centered.

**Comment by Jeremy7701** [comment]
Thanks, Clem

Not sure how I managed to put the Window list in the wrong zone; all fixed now.
