### ISSUE TITLE
cinnamon: icon theme doesn't load

### ISSUE THREAD

**Issue by DesertRat74** [linuxmint/lmde6-beta#13]
Installed an icon theme that shows in the theme dialog but it won't load when selected. This theme works fine in LM 21.2 and LMDE 6 in a VM.

**Comment by clefebvre** [comment]
Please provide us with the theme.

**Comment by DesertRat74** [comment]
@clefebvre 
You can remove this issue because it was caused by operator error. Seems  I was using a corrupted file.
