### ISSUE TITLE
Please don't publish stable release until my mintUpdate major upgrade implementation is ready

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/lmde6-beta#18]
@clefebvre Although this isn't a beta issue, I'd like to ask you if you could wait with the stable release until my mintUpdate major upgrade implementation is ready, if I don't need too much time. ;)

**Comment by clefebvre** [comment]
It won't affect this BETA. There are no PPA in LMDE. When it comes to Romeo, anything in Romeo should always be considered unstable.

**Comment by carlosmintfan** [comment]
@clefebvre I'm not talking about PPAs or Romeo - and as we talk about Romeo, please take a look at https://github.com/orgs/linuxmint/discussions/145 - but I'll make a pull request to https://github.com/linuxmint/mintupdate ;)
