### ISSUE TITLE
chromium: depends on pulseaudio

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/lmde6-beta#2]
![Screenshot from 2023-09-12 14-45-18](https://github.com/linuxmint/lmde6-beta/assets/63073056/768ecb26-6998-43e5-9a4d-dabfb41f7f50)

**Comment by anaximeno** [comment]
This seems to be caused by the complete move from pulseaudio to pipewire on debian, but in theory chromium should still work under pipewire since I was able to install google-chrome and it is working without any problems regarding audio.

**Comment by ghost** [comment]
You need to install manually 'PulseAudio sound server' through the Synaptic Package Manager or Software Manager. It seems it is not installed by default. After that try to install chromium again. Installation will be succesfull.

**Comment by anaximeno** [comment]
> You need to install manually 'PulseAudio sound server' through the Synaptic Package Manager or Software Manager. It seems it is not installed by default. After that try to install chromium again. Installation will be succesfull.

Yeah, that would be a way to install it. But I am suspecting that this would not be necessary since pipewire is already installed and google-chrome (which is based on chromium) does work even not having pulseaudio installed on the system. For what I know, pipewire also supports pulseaudio in its implementation, so there wouldn't be a need to have both them installed in the system.

**Comment by clefebvre** [comment]
Fixed in 117.x
