### ISSUE TITLE
mintupdate: No message about reboot needed after kernel update

### ISSUE THREAD

**Issue by Angedestenebres** [linuxmint/lmde6-beta#25]
As said in the title, see screens.

![VirtualBox_LMDE 6 beta no codec_17_09_2023_13_02_14](https://github.com/linuxmint/lmde6-beta/assets/21110485/5529db9c-b0db-4b60-9f34-521b9eb6b3c3)
![VirtualBox_LMDE 6 beta no codec_17_09_2023_13_07_00](https://github.com/linuxmint/lmde6-beta/assets/21110485/066628ef-4db1-42b0-ac43-03f233262f36)

**Comment by clefebvre** [comment]
Fixed in 6.0.5
