### ISSUE TITLE
Release notes: Issues with KDE apps

### ISSUE THREAD

**Issue by taneharre** [linuxmint/lmde6-beta#26]
The release notes for faye (https://linuxmint.com/rel_faye.php) advise installing kdelibs-bin kdelibs5-data kdelibs5-plugins if there are issues with KDE apps but these packages are not available in the repo.

**Comment by MiZoG99** [comment]
Copied over from an old LMDE release's notes obviously and not applicable on Faye?

**Comment by clefebvre** [comment]
Fixed.
