### ISSUE TITLE
Include pavucontrol to LMDE6

### ISSUE THREAD

**Issue by sebalips** [linuxmint/lmde6-beta#27]
It is not possible to record sounds from Firefox (website playing audio) with Audacity. To make it working I had to install pavucontrol (PulseAudio Volume Control), in the Record tab there is a dropdown menu "ALSA Capture from" that is by default set to internal analog audio (see screenshot). Once it is set to Monitor of internal analog audio, everything works fine. It has to be set only once. 

Would be convenient, if this setting is set by default, so that one does not have to install pavucontrol. 

![Screenshot from 2023-09-17 22-41-33](https://github.com/linuxmint/lmde6-beta/assets/78656028/049b7da3-b591-4ebb-84e8-57a2b8268e1b)

**Comment by sebalips** [comment]
To make dealing with audio record problems more user friendly please include pavucontrol to LMDE6.

**Comment by anaximeno** [comment]
> To make dealing with audio record problems more user friendly please include pavucontrol to LMDE6.

That can't be done in the sound settings?

**Comment by clefebvre** [comment]
Pavucontrol is recommended for troubleshooting and advanced manipulation. It's not something we want to have installed by default.

That said, we could probably add recording settings support in Cinnamon.

**Comment by sebalips** [comment]
This sound good. Will the recording settings than also be available in e.g. KDE if installed by the user?
The setting you have in mind, is this a package I can install and try in advance?
