### ISSUE TITLE
nemo: wrong filesizes displayed during copying

### ISSUE THREAD

**Issue by Hawaiihemd** [linuxmint/lmde6-beta#29]
Just tried out lmde 6 beta on my 32-bit machine and realized [this bug](https://github.com/linuxmint/nemo/issues/3154) is still in the wild in v5.8.4.

Just wanted to point that out as I received no feedback on that issue whatsoever.

If this is a "won't fix" please let me know. I can live with that ;)

**Comment by mtwebster** [comment]
I think this needs to be a 'won't fix' for the moment, though I'll leave the original bug open. This is an issue with some code not being able to handle 64 bit numbers correctly (which is what disk/file sizes are stored in) on a 32 bit machine.

I can't fix the problematic code directly (it's not part of nemo) but can rework how these sizes are formatted. It's just not something that can be done quickly (and without risk of additional problems).

**Comment by Hawaiihemd** [comment]
I understand.
Thank you for the insight and for looking into it!
