### ISSUE TITLE
Gdebi broken; it cannot install any local package.

### ISSUE THREAD

**Issue by harlekin777** [linuxmint/lmde6-beta#30]
After pushing "Install Package" Gdebi freezes and cannot proceed. It issues this error message: 

"org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."

Gdebi window cannot be closed any more. Local package is not installed.

Apparently the Mint version of Gdebi is very old and breaks LMDE 6 (same as LMDE 5 also). The original Gdebi in Debian 11 and 12 works flawlessly. Would it not be better to keep upstream versions when possible and avoid maintenance of own packages which are not essential? It would allow you to focus more on Cinnamon itself (the best desktop IMHO).

**Comment by MiZoG99** [comment]
Cannot reproduce it.
Just installed latest deb package of [freetube](https://freetubeapp.io/#download) and [Lutris](https://github.com/lutris/lutris/releases) via gdebi on LMDE6 beta with no problem whatsoever.
Moreover, Gdebi is on the same version (0.9.5.7) everywhere, Debian 12, Ubuntu 22.04 LTS, main Mint, LMDE. It hasn't seen a new release in ages.
In fact, in my experience, Gdebi has not been working smoothly "upstream" (Debian 12.1 Xfce) where it fails to install packages when associated with .deb. It runs normally though in a terminal and when you change "Terminal=false" to "true" in its menu entry.
So something else is happening there, harlekin777 either related to your software sources configuration or to the specific packages you try to install.
Right click in the folder where those packages are stored, pick "Open in Terminal", run "sudo apt install ./nameofyourpackage.deb" and see if any error messages print out in the terminal.

**Comment by harlekin777** [comment]
Sorry for my wrong conclusions. Moreover, I found the reason for the problem. I made a mistake in editing manually the official-package-repositories.list. After fixing it Gdebi runs smoothly. No problem any more. I apologize for wasting your time. Thank you for your patient explanation!
This issue can be closed.
