### ISSUE TITLE
live-installer: Wrong device formatted when user agrees to format an unreadable device

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/lmde6-beta#31]
This bug happens if the following conditions are met:

– The BETA ISO is installed alongside devices containing valuable data
– An unreadable device is present on the computer (typically a card reader with no card in it)
– When the installer complains it cannot read the device and asks whether to format it, YES is pressed

Instead of formatting the unreadable device the installer formats the device that was previously detected.

The bug was introduced in live-installer 2023.09.07 by https://github.com/linuxmint/live-installer/commit/ad29db2ebf2a8a9e12302e3fe190f881efec4ca4.

It was fixed in live-installer 2023.09.19.2 by https://github.com/linuxmint/live-installer/commit/9a718e3d74920d7a74838b24d43948be5142b811.

It affects the following ISOs:

0e10648c53abb4ebb5d0d012a6f1f918f2ac4c4b943bf49a0b43bbdd72d38ea1 *lmde-6-cinnamon-32bit-beta.iso
cb2e0e4cecfb4e112ae44f1ffabfcb54d1fce85faca4595e33fd0243626344b1 *lmde-6-cinnamon-64bit-beta.iso

It's fixed in the following ISOS:

f9b8248c89420f9d8144406321a9fb17d4999cbb5950b8ad39a9748011def08f *lmde-6-cinnamon-32bit-beta2.iso
d6e2fb01d60230687b4308b583b4bdad39ea4765d8e92f46b9c969f5f4199876 *lmde-6-cinnamon-64bit-beta2.iso

**Comment by IvanDeFelice76** [comment]
![IMG_20230923_183619](https://github.com/linuxmint/lmde6-beta/assets/26720956/0c82e9c7-eb5c-4692-9a19-d2b5026b1c16)


Notebook Asus X555LP
