### ISSUE TITLE
installer tries to guess use language instead of either using english or the language from the current LMDE

### ISSUE THREAD

**Issue by froeb** [linuxmint/lmde6-beta#33]
I am a German who speaks English and German and I am living in Portugal. I do however *NOT* speak Portugese.
I observer that many websites want to be clever and detect from my ip address that i am in Portugal and by default switch to Portugese, inseatd of using my preferences which i have configured in my browser.

In a similar way, the installer seems to detect (from my ip?) that i am in Portugal and starts the process in Portugese. There is no way to switch it to English or another language.

When the Live CD, from which the installation happens is in English and has not scared of the people wanting to install LMDE so far, then i would expect the installation either be in English or you could choose yourself the language by boot parameter, by changing the language in the settings (doesn't seem to work in the live CD as long as system is not installed. btw) or at the very first start of the installation process.

However, i have to admit that the language of the installation process can be changed directly in the second screen after the lets start welcome box in Portugese (in my case, being in Portugal)

I consider this a very minor issue for myself, as it can be addressed in the second step. However, some less brave people might never dare to continue to that second step when they are greeted in a foreign language (consider an US American setting up his notebook while being in China or Russia, so being greeted not only by another language but also by a set of strange, non western charachters)

**Comment by clefebvre** [comment]
I understand your point of view @froeb but I think you're the minority case here.

For a vast majority of people, whose location match their primary language, this is very convenient. It reduces step 2 to just a click on the Next button. They don't need to find their language.

Among the remaining minority, you've got expats and tourists. I'd like to think most expats can speak the local language to some extent at least, as for tourists.. how likely are they to reinstall their OS while on vacation?

I get your point but I won't make it worse for most people just to make it better for just a few people.
