### ISSUE TITLE
Broadcast Message at Shutdown

### ISSUE THREAD

**Issue by He-Zu** [linuxmint/lmde6-beta#34]
When shutdown system get the following message on the screen. 

Broadcast Message from “User@hostname (date time)
The system will power off now!”

Is it possible to turn off or hide this message?

**Comment by clefebvre** [comment]
It is but that's a support question, not a bug.

You can either raise the loglevel or replace calls to shutdown with shutdown --no-wall.. or use msg maybe. There are probably many ways to achieve this. Though I never tried any personally.
