### ISSUE TITLE
Virtual box versioning

### ISSUE THREAD

**Issue by Jeremy7701** [linuxmint/lmde6-beta#35]
In LMDE5, virtualbox is available as 6.1 and 7.0
I'd suggest that an upgrade is required in LMDE5 before moving to LMDE6.
The instructions I found are non-trivial - https://kifarunix.com/upgrade-virtualbox-6-x-to-virtualbox-7-x-on-ubuntu-debian/?expand_article=1

I didn't do this the first time and had problems in running a LMDE6 VM.
Unfortunately, I didn't document what I was doing.

I now have everything sorted, following the upgrade to 7.0, done properly.

**Comment by clefebvre** [comment]
Hi @Jeremy7701,

I usually get the latest directly from the Virtualbox website. They provide deb packages for Debian 12: https://download.virtualbox.org/virtualbox/7.0.10/virtualbox-7.0_7.0.10-158379~Debian~bookworm_amd64.deb.

Note that we don't package vbox ourselves. This is done by Debian.
