### ISSUE TITLE
xed: line numbers unreadable with dark themes

### ISSUE THREAD

**Issue by anaximeno** [linuxmint/lmde6-beta#5]
When the 'display line num' option is disabled it will show this white line at the left border of the window:
![Screenshot from 2023-09-12 14-43-53](https://github.com/linuxmint/lmde6-beta/assets/63073056/05642d01-c2e8-4761-a904-cefc84da5c74)

If you enable the display line num option:

![Screenshot from 2023-09-12 14-43-08](https://github.com/linuxmint/lmde6-beta/assets/63073056/5a2ce76c-615b-42cd-abfa-633cd9724463)

If you enable the 'Highlight current selection' it will be almost unreadable as well

**Comment by clefebvre** [comment]
Go to Edit -> Preferences and change the gtksourceview theme.

![image](https://github.com/linuxmint/lmde6-beta/assets/1138515/f5e4cfad-3b36-48df-9d8c-d3a2cdc54333)

The default theme only works well with light themes. That's a limitation of gtksourceview 4 I'm afraid. It has no concept of light/dark.

It looks like support was added in gtksourceview 5, but that's using GTK4 so it's not something we'll be using right now.
