### ISSUE TITLE
live-installer: filesystem.squashfs not found

### ISSUE THREAD

**Issue by sammycda** [linuxmint/lmde6-beta#6]
When I try to install the beta on my Dell XPS13-9300 from the command line, i keep getting the error message “Critical Error: Live medium (run/live/medium/live/filesystem.squashfs) not found!”
When I try to click on the Install Linux Mint icon on the desktop, nothing happens.

I've used Rufus in Windows, BalenaEtcher and the USB Writer app in linux. I've also tried multiple USB drives. The drives created with BalenaEtcher and USB Image Writer will not even boot.

Debian "bookworm" installs fine using the same USB drives on the same system.

LMDE 5 installs fine using the same USB install media, after disabling secure boot.

**Comment by sammycda** [comment]
Clem,
The output is from a USB drive created with Rufus. Drives created from BalenaEtcher and USB Image Writer will not boot. Here is the output:

mint@mint:~$ mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=16106140k,nr_inodes=4026535,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=3232300k,mode=755,inode64)
/dev/sda1 on /run/live/medium type vfat (ro,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro)
/dev/loop0 on /run/live/rootfs/filesystem.squashfs type squashfs (ro,noatime,errors=continue)
tmpfs on /run/live/overlay type tmpfs (rw,noatime,size=16161496k,mode=755,inode64)
overlay on / type overlay (rw,noatime,lowerdir=/run/live/rootfs/filesystem.squashfs/,upperdir=/run/live/overlay/rw,workdir=/run/live/overlay/work,redirect_dir=on)
tmpfs on /usr/lib/live/mount type tmpfs (rw,nosuid,nodev,noexec,relatime,size=3232300k,mode=755,inode64)
/dev/sda1 on /usr/lib/live/mount/medium type vfat (ro,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro)
/dev/loop0 on /usr/lib/live/mount/rootfs/filesystem.squashfs type squashfs (ro,noatime,errors=continue)
tmpfs on /usr/lib/live/mount/overlay type tmpfs (rw,noatime,size=16161496k,mode=755,inode64)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=16932)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
ramfs on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
ramfs on /run/credentials/systemd-tmpfiles-setup-dev.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
ramfs on /run/credentials/systemd-sysctl.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,relatime,inode64)
ramfs on /run/credentials/systemd-tmpfiles-setup.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=3232296k,nr_inodes=808074,mode=700,uid=1000,gid=1000,inode64)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
mint@mint:~$

**Comment by clefebvre** [comment]
This is the 64-bit ISO?

Tested balenaEtcher -> works OK. It mounts the squashfs in the correct path, the only diff is that it's sdb1 not sr0.

**Comment by clefebvre** [comment]
I can reproduce the issue with Rufus, choosing all the default options (ISO mode, vfat, etc..).

So.. the issue is that Rufus basically doesn't copy symbolic links.

on this ISO, live is a symbolic to casper.

If you use Rufus you end up with a "live" empty file.. so there's no live/filesystem.squashfs in /run/live/medium.

There's a casper/filesystem.squashfs.

**Comment by clefebvre** [comment]
Traditionally in LMDE we've always put things in /live, we had no /casper. What we're doing right now since we updated our ISO production tools is that we build Mint and LMDE the same way, and live is now a symlink to casper.

**Comment by sammycda** [comment]
Clem, I'm not sure what you are telling me? How should I make the USB stick? Use "dd" from the linux terminal or an app? When I use BalenaEtcher or USB Image Writer, the USB stick won't boot on the laptop.

**Comment by clefebvre** [comment]
That's a separate issue. This issue is about the live-installer not finding the squashfs file and therefore not starting.

I don't have enough info to understand why the ISO doesn't boot for you with mintstick or balenaEtcher.

**Comment by clefebvre** [comment]
Fixed in live-installer 2023.09.14.
