### ISSUE TITLE
grub: /etc/default/grub gets overwritten

### ISSUE THREAD

**Issue by MiZoGf** [linuxmint/lmde6-beta#8]
Fresh installation of beta. I tried to get rid of acpi error and "no sgx found" boot-up messages by adding "loglevel=3" to my grub configuration with **sudo nano /etc/default/grub**

After editing it looks like this:

```
GRUB_DEFAULT=0
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=3"
GRUB_CMDLINE_LINUX=""
```
I executed **sudo update-grub** to apply changes and rebooted the system. This had no effect.
My guess changes to /default/grub are overridden by **/etc/default/grub.d/50_lmde.cfg**. I could perhaps apply my changes there.
I chose instead to edit /boot/grub/grub.cfg directly to add the extra argument. This is I know generally not recommended.
The question is can editing of /etc/default/grub work as expected? It is the default way to add boot arguments in Debian, Ubuntu and Mint main. Most guides, how/tos about grub configuration take it as granted.

[Full system specs](https://termbin.com/u8pk)

**Comment by clefebvre** [comment]
Hi @MiZoGf 

I'd recommend to do it in **/etc/default/grub.d/51_loglevel.cfg** instead.

```
#! /bin/sh
set -e

GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=3"
```

This should override what 50_lmde.cfg does and not interfere with future updates of debian-system-adjustments.
